# Generated by Django 2.2.13 on 2020-07-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38)),
                ('keyword', models.CharField(max_length=56)),
                ('description', models.CharField(max_length=156)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reads', models.IntegerField(default=10)),
                ('agree', models.IntegerField(default=5)),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='%Y%m%d/thumbnail')),
                ('is_delete', models.BooleanField(default=False)),
                ('Author', models.CharField(default='admin', max_length=18)),
                ('ownername', models.CharField(max_length=18, null=True)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ColumnName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=38)),
                ('keyword', models.CharField(max_length=56)),
                ('description', models.CharField(max_length=156)),
                ('path', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'ColumnName',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigImg', models.ImageField(upload_to='%Y%m%d/bigimg')),
                ('name', models.CharField(max_length=38)),
                ('alt', models.CharField(max_length=38)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=23)),
                ('headimg', models.ImageField(default='headimg.png', upload_to='')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('agree', models.IntegerField(default=2)),
                ('disagree', models.IntegerField(default=0)),
                ('column', models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.ColumnName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='ArticleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('agree', models.IntegerField(default=2)),
                ('disagree', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
            options={
                'db_table': 'ArticleMessage',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ColumnName'),
        ),
    ]
