# Generated by Django 2.2.13 on 2020-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='next',
            field=models.IntegerField(null=True),
        ),
    ]
