# Generated by Django 2.2.13 on 2020-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200726_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='next',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
