# Generated by Django 2.2.13 on 2020-07-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200727_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
