# Generated by Django 2.2.13 on 2020-07-31 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200730_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
            options={
                'db_table': 'MessageAgree',
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='ArticleMessageAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.IntegerField(default=0)),
                ('articleMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ArticleMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
            options={
                'db_table': 'ArticleMessageAgree',
                'unique_together': {('user', 'articleMessage')},
            },
        ),
    ]
