# Generated by Django 2.2.13 on 2020-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200731_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemessage',
            name='agree',
            field=models.IntegerField(default=0),
        ),
    ]
