# Generated by Django 2.2.13 on 2020-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200801_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(default='headimg.png', upload_to='%Y%m%d/image'),
        ),
    ]
